ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "isCashSale" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "cashReceived" DECIMAL(10,2);
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "cashChange" DECIMAL(10,2);
