ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "subsidyEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "subsidyMealsPerDay" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "subsidyMealsPerDay" INTEGER;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "isSubsidized" BOOLEAN NOT NULL DEFAULT false;
