ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "menuRotationMode" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "manualMenuName" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "manualMenuPrice" DECIMAL(10,2);
